CREATE TABLE YEAR_TABLE (
  id_year INTEGER(4) PRIMARY KEY
);

CREATE TABLE MONTH_TABLE (
    id_month INTEGER    PRIMARY KEY AUTOINCREMENT,
    id_year  INTEGER(4) NOT NULL REFERENCES YEAR_TABLE(id_year) ON DELETE CASCADE
);

CREATE TABLE SALE (
    id       INTEGER   PRIMARY KEY AUTOINCREMENT,
    valor    NUMBER    NOT NULL,
    id_month INTEGER   NOT NULL REFERENCES MONTH_TABLE(id_month) ON DELETE CASCADE
);

CREATE TABLE PURCHASE (
    id       INTEGER   PRIMARY KEY AUTOINCREMENT,
    valor    NUMBER    NOT NULL,
    id_month INTEGER   NOT NULL REFERENCES MONTH_TABLE(id_month) ON DELETE CASCADE
);

CREATE UNIQUE INDEX id ON SALE (id);
CREATE UNIQUE INDEX id ON PURCHASE (id);